name: PR Checks

on:
  pull_request:
    branches: [master]

jobs:
  pr-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate PR title (Conventional Commits)
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            chore
            refactor
            test
            ci
          requireScope: false

      - name: Check for merge conflicts
        run: |
          git fetch origin master
          git merge-base --is-ancestor origin/master HEAD || exit 1

      - name: Validate branch naming
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ ! "$BRANCH_NAME" =~ ^(feat|fix|refactor|release)/[A-Za-z0-9-]+ ]]; then
            echo "Branch name does not follow convention: feat|fix|refactor|release/<name>"
            exit 1
          fi
